# Generated by Django 5.2.17 on 2026-09-03 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormativaPensional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=220)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_efectos', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_juridico', models.CharField(choices=[('vigente', 'Vigente'), ('suspendida', 'Suspendida'), ('vigente_parcial', 'Vigente parcialmente'), ('derogada', 'Derogada'), ('condicionada', 'Condicionada'), ('pendiente_control', 'Pendiente control constitucional'), ('discutible', 'Discutible')], max_length=40)),
                ('fuente', models.URLField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PensionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(default='borrador', max_length=40)),
                ('source', models.CharField(max_length=240)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='pensiones.normativapensional')),
            ],
            options={
                'unique_together': {('normativa', 'code')},
            },
        ),
    ]
