# Generated by Django 5.2.17 on 2026-09-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondoPensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('regimen', models.CharField(choices=[('rpm', 'Prima Media - Colpensiones'), ('rais', 'Ahorro Individual - AFP privada'), ('accai', 'ACCAI Ley 2381')], max_length=20)),
                ('entidad', models.CharField(blank=True, max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fuente', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['regimen', 'nombre'],
            },
        ),
    ]
