# Generated by Django 5.2.17 on 2026-09-03 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('es_cierre', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, max_length=120)),
                ('campana', models.CharField(blank=True, max_length=120)),
                ('producto_interes', models.CharField(blank=True, max_length=160)),
                ('valor_potencial', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('probabilidad', models.PositiveSmallIntegerField(default=10)),
                ('temperatura', models.CharField(choices=[('frio', 'Frio'), ('tibio', 'Tibio'), ('caliente', 'Caliente')], default='tibio', max_length=20)),
                ('prioridad', models.PositiveSmallIntegerField(default=3)),
                ('proximo_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('motivo_perdida', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='clientes.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.pipelinestage')),
            ],
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_etapas', to='leads.lead')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.pipelinestage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.pipelinestage')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(default='llamada', max_length=60)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('resultado', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='leads.lead')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['consultor', 'etapa'], name='leads_lead_consult_c33e67_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['proximo_seguimiento'], name='leads_lead_proximo_7649d7_idx'),
        ),
    ]
