# Generated by Django 5.2.17 on 2026-09-03 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('visitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultoriaCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('diagnostico', 'Diagnostico'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('datos_personales', models.JSONField(blank=True, default=dict)),
                ('situacion_laboral', models.JSONField(blank=True, default=dict)),
                ('informacion_economica', models.JSONField(blank=True, default=dict)),
                ('informacion_pensional', models.JSONField(blank=True, default=dict)),
                ('historia_cotizacion', models.JSONField(blank=True, default=dict)),
                ('familia_dependientes', models.JSONField(blank=True, default=dict)),
                ('coberturas_actuales', models.JSONField(blank=True, default=dict)),
                ('objetivos', models.JSONField(blank=True, default=dict)),
                ('diagnostico', models.TextField(blank=True)),
                ('oportunidades', models.TextField(blank=True)),
                ('proximos_pasos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultorias', to='clientes.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultorias', to='visitas.visita')),
            ],
        ),
    ]
