# Generated by Django 5.2.17 on 2026-09-03 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('modalidad', models.CharField(default='Presencial', max_length=60)),
                ('ubicacion', models.CharField(blank=True, max_length=240)),
                ('objetivo', models.CharField(blank=True, max_length=220)),
                ('motivo', models.TextField(blank=True)),
                ('asistentes', models.TextField(blank=True)),
                ('situacion_actual', models.TextField(blank=True)),
                ('necesidades_detectadas', models.TextField(blank=True)),
                ('informacion_recopilada', models.JSONField(blank=True, default=dict)),
                ('productos_discutidos', models.TextField(blank=True)),
                ('simulaciones_realizadas', models.TextField(blank=True)),
                ('conclusiones', models.TextField(blank=True)),
                ('compromisos_cliente', models.TextField(blank=True)),
                ('compromisos_consultor', models.TextField(blank=True)),
                ('proxima_accion', models.CharField(blank=True, max_length=180)),
                ('fecha_proxima_accion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_privadas', models.TextField(blank=True)),
                ('archivo_adjunto', models.FileField(blank=True, upload_to='visitas/')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada'), ('no_asistio', 'No asistio')], default='programada', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='clientes.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
                'indexes': [models.Index(fields=['consultor', 'fecha'], name='visitas_vis_consult_9321ac_idx'), models.Index(fields=['cliente', 'fecha'], name='visitas_vis_cliente_a4ee5d_idx')],
            },
        ),
    ]
