# Generated by Django 5.2.17 on 2026-09-03 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoProteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesidad_fallecimiento', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('necesidad_invalidez', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('necesidad_educacion', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cobertura_existente', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('conclusiones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_proteccion', to='clientes.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoberturaExistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('proveedor', models.CharField(blank=True, max_length=160)),
                ('valor_asegurado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='seguros.diagnosticoproteccion')),
            ],
        ),
    ]
