# Generated by Django 5.2.17 on 2026-09-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=160)),
                ('proveedor', models.CharField(blank=True, max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('caracteristicas', models.JSONField(blank=True, default=dict)),
                ('requisitos', models.TextField(blank=True)),
                ('documentacion', models.TextField(blank=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
