# Generated by Django 5.2.17 on 2026-09-03 00:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Natural'), ('juridica', 'Juridica')], default='natural', max_length=20)),
                ('tipo_documento', models.CharField(blank=True, max_length=20)),
                ('numero_documento', models.CharField(blank=True, db_index=True, max_length=40)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('estado_civil', models.CharField(blank=True, max_length=40)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=240)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ocupacion', models.CharField(blank=True, max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('origen', models.CharField(blank=True, max_length=120)),
                ('segmento', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('prospecto', 'Prospecto'), ('activo', 'Cliente activo'), ('inactivo', 'Inactivo')], default='prospecto', max_length=30)),
                ('etiquetas', models.CharField(blank=True, max_length=250)),
                ('ingresos', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('ingresos_adicionales', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('gastos_estimados', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('activos', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('pasivos', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('personas_a_cargo', models.PositiveSmallIntegerField(default=0)),
                ('capacidad_ahorro', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('ultima_interaccion', models.DateTimeField(blank=True, null=True)),
                ('proxima_accion', models.CharField(blank=True, max_length=180)),
                ('proxima_accion_fecha', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidad', models.TextField()),
                ('autorizado', models.BooleanField(default=False)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=120)),
                ('evidencia', models.FileField(blank=True, upload_to='consentimientos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('object_label', models.CharField(blank=True, max_length=180)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['consultor', 'estado'], name='clientes_cl_consult_03c89d_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_documento'], name='clientes_cl_numero__868cb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento', ''), _negated=True), fields=('tipo_documento', 'numero_documento'), name='unique_cliente_documento_no_vacio'),
        ),
    ]
